### ISSUE TITLE
ProtectedClassMemberSniff

### ISSUE THREAD

**Issue by martinboy** [magento/marketplace-eqp#10]
It looks like the following Pull request 84192d436966a9f93810d9269672b59c775d48bd had to fix 
not a typo but change a sniff to at least  PrivateClassMemberSniff like it is in MEQP1 standard. 

But in general what is the nature of the following sniffs? Why using of private/protected members is a bad practice?

**Comment by lenaorobei** [comment]
@martinboy, this sniff is correct, it warns Magento 2 developers that all nop-public methods and properties should be private. Please, follow here #7 for the detailed explanation and related links.

**Comment by lenaorobei** [comment]
#7
