### ISSUE TITLE
Does MEQP2 use MEQP1 rules?

### ISSUE THREAD

**Issue by tylers-username** [magento/marketplace-eqp#101]
I'm sniffing with `/vendor/bin/phpcs . --standard=MEQP2` and am seeing this rule being caught: `MEQP1.Security.DiscouragedFunction.Found`.

Is this a misconfiguration on my part or is this expected behavior?

**Comment by lenaorobei** [comment]
@tylerssn this is expected behavior. MEQP2 ruleset [include some sniffs from MEQP1](https://github.com/magento/marketplace-eqp/blob/master/MEQP2/ruleset.xml#L21).
