### ISSUE TITLE
Failing Code Sniffer due to MEQP1 lib bug

### ISSUE THREAD

**Issue by rs-bryan** [magento/marketplace-eqp#106]
Uploading our package suddenly fails the automated QA code sniffer. 

[This](https://github.com/magento/marketplace-eqp/pull/105) card fixes the issue (tested our changes locally).

Is there an estimated release date for this PR? We have critical changes that we need to get out.

**Comment by lenaorobei** [comment]
@rs-bryan thanks for reporting. We are working on new release.
