### ISSUE TITLE
Current configuration not useful for Marketplace Technical Review

### ISSUE THREAD

**Issue by powli** [magento/marketplace-eqp#11]
I don't know if this coding standard was ever intended for it (the naming marketplace-eqp suggests it though), but with the current configuration it is not useful to preview the Magento Marketplace technical review.

The technical review mostly uses the [Code Validation Guidelines](http://docs.magento.com/marketplace/user_guide/extensions/review-code-validation.html) with some undocumented additions. The current rulesets for MEQP1 and MEQP2 do not define the severity or change the rules/sniffs that would block the technical review from passing to the error type.

I guess developers using any kind of CI to automatically perform static code analysis would appreciate to have the possibility to let their builds fail, if they would not pass the Marketplace technical review.

**Comment by erikhansen** [comment]
I agree with this issue. I ran this tool against a M2 extension and after addressing many of the issues raised by this tool, I submitted the extension to the Magento Marketplace. However the Marketplace's technical review returned a number of additional issues that this tool didn't catch.

At the very least, the readme of this repo should be updated to state that there is a significant difference in the results of this tool vs the Magento Marketplace scan.

**Comment by lenaorobei** [comment]
@powli that's a good idea! We took a note of this and will work on providing an easier tool for developers to have an ability to test their extension on Marketplace before uploading. 

@erikhansen could you please give some examples of issues, that was found on Magento Marketplace Technical Review and wasn't found by MEQP2 sniffs? I will appreciate that much because it sounds really strange. Marketplace Technical Review, namely, static code check is based on this coding standard.

**Comment by powli** [comment]
@lenaorobei FYI we have found the following issues with the current state of this coding standard in regards to the technical review:
1. Severities all have the value 5 (phpcs default value) which does not match with the [guidelines](http://docs.magento.com/marketplace/user_guide/extensions/review-code-validation.html)
2. Violation types do not match with guidelinse (ruleset has them as warning, guidelines mention errors)
   - MEQP1.Security.LanguageConstruct
   - MEQP1.Strings.RegEx.PossibleExecutableRegEx
   - MEQP1.Strings.StringPosition.ImproperValueTesting
3. Many rules are not documented and one rule is documented but not actually contained, you can check with: `phpcs -vvv --standard=MEQP1 composer.json | grep Registered | awk '{print $2}' | sed 's/[\_]/./g' | sed 's/Sniffs\.//' | sed 's/Sniff$//' | sort`

| Docs | CS Rules |
| --- | --- |
| Generic.Arrays.DisallowShortArraySyntax.Found | Generic.Arrays.DisallowShortArraySyntax |
| Generic.Classes.DuplicateClassName.Found | Generic.Classes.DuplicateClassName |
|   | Generic.CodeAnalysis.ForLoopShouldBeWhileLoop |
|   | Generic.CodeAnalysis.ForLoopWithTestFunctionCall |
| Generic.CodeAnalysis.JumbledIncrementer.Found | Generic.CodeAnalysis.JumbledIncrementer |
|   | Generic.CodeAnalysis.UnconditionalIfStatement |
|   | Generic.CodeAnalysis.UnnecessaryFinalModifier |
|   | Generic.CodeAnalysis.UnusedFunctionParameter |
|   | Generic.CodeAnalysis.UselessOverridingMethod |
|   | Generic.Commenting.Fixme |
|   | Generic.Commenting.Todo |
|   | Generic.Files.ByteOrderMark |
|   | Generic.Files.LineEndings |
|   | Generic.Files.LineLength |
|   | Generic.Files.OneClassPerFile |
|   | Generic.Files.OneInterfacePerFile |
| Generic.Functions.CallTimePassByReference.NotAllowed | Generic.Functions.CallTimePassByReference |
|   | Generic.Functions.FunctionCallArgumentSpacing |
|   | Generic.Functions.OpeningFunctionBraceBsdAllman |
| Generic.Metrics.CyclomaticComplexity.[MaxExceeded,TooHigh] | Generic.Metrics.CyclomaticComplexity |
| Generic.Metrics.NestingLevel.[MaxExceeded,TooHigh] | Generic.Metrics.NestingLevel |
| Generic.PHP.CharacterBeforePHPOpeningTag.Found | Generic.PHP.CharacterBeforePHPOpeningTag |
| Generic.PHP.DeprecatedFunctions.Deprecated | Generic.PHP.DeprecatedFunctions |
|   | Generic.PHP.DisallowShortOpenTag |
| Generic.PHP.NoSilencedErrors.Discouraged | Generic.PHP.NoSilencedErrors |
|   | Generic.WhiteSpace.DisallowTabIndent |
|   | MEQP1.Classes.Mysql4 |
| MEQP1.Classes.ObjectInstantiation.FoundDirectInstantiation | MEQP1.Classes.ObjectInstantiation |
| MEQP1.Classes.ResourceModel.OutsideOfResourceModel | MEQP1.Classes.ResourceModel |
|   | MEQP1.CodeAnalysis.EmptyBlock |
|   | MEQP1.Exceptions.DirectThrow |
| MEQP1.Exceptions.Namespace.NotFoundNamespace | MEQP1.Exceptions.Namespace |
| MEQP1.Performance.CollectionCount.FoundCollectionCount | MEQP1.Performance.CollectionCount |
| MEQP1.Performance.FetchAll.FoundFetchAll | MEQP1.Performance.FetchAll |
| MEQP1.Performance.GetFirstItem.FoundGetFirstItem | MEQP1.Performance.GetFirstItem |
| MEQP1.Performance.Loop.[ArraySize,DataLoad,ModelLSD] | MEQP1.Performance.Loop |
| MEQP1.PHP.Goto.FoundGoto | MEQP1.PHP.Goto |
|   | MEQP1.PHP.PrivateClassMember |
| MEQP1.PHP.Syntax.PHPSyntax | MEQP1.PHP.Syntax |
| MEQP1.PHP.Var.FoundVar | MEQP1.PHP.Var |
| MEQP1.Security.Acl.MissingAclMethod | MEQP1.Security.Acl |
|   | MEQP1.Security.DiscouragedFunction |
| MEQP1.Security.IncludeFile.FoundIncludeFile | MEQP1.Security.IncludeFile |
| MEQP1.Security.LanguageConstruct.[DirectOutput,ExitUsage,WrongBackQuotesUsage] | MEQP1.Security.LanguageConstruct |
| MEQP1.Security.Superglobal.SuperglobalUsageError | MEQP1.Security.Superglobal |
| MEQP1.SQL.MissedIndexes.MissedIndexes | MEQP1.SQL.MissedIndexes |
| MEQP1.SQL.RawQuery.FoundRawSql | MEQP1.SQL.RawQuery |
| MEQP1.SQL.SlowQuery.[FoundSlowRawSql,FoundSlowSql] | MEQP1.SQL.SlowQuery |
|   | MEQP1.Stdlib.DateTime |
| MEQP1.Strings.RegEx.PossibleExecutableRegEx | MEQP1.Strings.RegEx |
| MEQP1.Strings.StringConcat.ImproperStringConcatenation | MEQP1.Strings.StringConcat |
| MEQP1.Strings.StringPosition.ImproperValueTesting | MEQP1.Strings.StringPosition |
|   | PEAR.Classes.ClassDeclaration |
|   | PEAR.ControlStructures.ControlSignature |
|   | PEAR.Functions.FunctionCallSignature |
|   | PEAR.Functions.ValidDefaultValue |
|   | PEAR.WhiteSpace.ScopeClosingBrace |
| PSR1.Classes.ClassDeclaration.MultipleClasses |   |
| Squiz.Functions.GlobalFunction.Found | Squiz.Functions.GlobalFunction |
|   | Squiz.Operators.IncrementDecrementUsage |
|   | Squiz.PHP.CommentedOutCode |
|   | Squiz.PHP.DiscouragedFunctions |
| Squiz.PHP.Eval.Discouraged | Squiz.PHP.Eval |
| Squiz.PHP.GlobalKeyword.NotAllowed | Squiz.PHP.GlobalKeyword |
|   | Squiz.PHP.NonExecutableCode |
|   | Squiz.Scope.MemberVarScope |
|   | Squiz.Scope.MethodScope |
|   | Zend.Debug.CodeAnalyzer |
| Zend.Files.ClosingTag.NotAllowed | Zend.Files.ClosingTag |
|   | Zend.NamingConventions.ValidVariableName |

We'll provide a pull request to fix most of the stuff for the MEQP1 standard.

Edit:
Latest commit also has the adjustments for the MEQP2 standard.

**Comment by lenaorobei** [comment]
@powli, unfortunately, we cannot accept you pull request because the main goal of MEQP coding standard is to encourage developers to fix all the issues, not just severity 10 and improve overall extensions quality. This coding standard is used not only on Marketplace but also for other checks so we would like to keep them more common and do not hardcode any values.

**Comment by mam08ixo** [comment]
As long as the `phpcs` parameters `--error-severity` or `--warning-severity` are not explicitly set, the report will remain the same as before. Developers are still able to "fix all the issues".

The name of this repository as well as the [Marketplace Extension Quality Program Update](https://magento.com/blog/technical/marketplace-extension-quality-program-update) blog post suggest this standard being published for exactly one purpose: Marketplace Level 1 technical review.
If this is not true:
- Please clarify the actual purpose in a prominent manner.
- Why should anyone use this coding standard in favour of the ECG or any other Magento related standard?

**Comment by ikruchynskyi** [comment]
@mam08ixo @powli ,
Thank you for your suggestions. We implemented such mechanism in 256f4fe981942f1f695714f45bc38b3ca8f311e8 and it's already in master. Now you can run phpcs with '--severity=10' option.
