### ISSUE TITLE
Create 1.0.3 tag

### ISSUE THREAD

**Issue by danslo** [magento/marketplace-eqp#14]
Hello,

Composer.json [was updated](https://github.com/magento/marketplace-eqp/commit/d3fd6bf04a2f1ea8950e589cb4725f81816b7e0d#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R3) to be version 1.0.3, but there exists no such tag in the repository.

Could you tag version 1.0.3? Thank you :)

**Comment by lenaorobei** [comment]
Added new release.

**Comment by bnchdrff** [comment]
i'm seeing 1.0.2 as the latest release on the repo.magento.com packagist -- did this make it through?
