### ISSUE TITLE
composer require magento/marketplace-eqp

### ISSUE THREAD

**Issue by serzhik** [magento/marketplace-eqp#2]
After I run `composer require magento/marketplace-eqp`
I get error:

```
[InvalidArgumentException]
  Could not find package magento/marketplace-eqp at any version for your mi
  nimum-stability (alpha). Check the package spelling or your minimum-stabi
  lity
```

**Comment by lenaorobei** [comment]
@Serzhik, thank you for reporting. Now we have some troubles with adding our repo to Packagist. We will fix it as soon as possible.
To make it work now you should add the repository to composer.json file by running `composer config repositories.magento-eqp git https://github.com/magento/marketplace-eqp`
And after that run `composer require magento/marketplace-eqp`.

**Comment by mehdichaouch** [comment]
```composer config repositories.magento-eqp git https://github.com/magento/marketplace-eqp``` is also a solution for error like :
```bash
$ composer require magento/marketplace-eqp:dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/marketplace-eqp dev-master exists as magento/marketplace-eqp[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5] but these are rejected by your constraint.
```

![image](https://user-images.githubusercontent.com/861701/34545531-e10e613c-f0ed-11e7-85da-778144962646.png)

**Comment by lenaorobei** [comment]
@mehdichaouch cannot reproduce this behavior. I just installed in this way successfully.
Could you please provide detailed steps to reproduce and `composer.json` file)?

**Comment by mehdichaouch** [comment]
@lenaorobei to allow us to run multi build from PHP 5.3 to 7.0, I do the install of ```marketplace-eqp``` via Travis only if ```$TRAVIS_PHP_VERSION``` >= 5.6.

To have more details, you can check this [Travis file](https://github.com/oystparis/oyst-1click-magento/blob/master/.travis.yml#L88) and the [composer file](https://github.com/oystparis/oyst-1click-magento/blob/master/composer.json).
If I don't have this, in my ```composer.json```:
```
    "repositories": {
        "magento-eqp": {
            "type": "git",
            "url": "https://github.com/magento/marketplace-eqp"
        }
```
I get error in [Travis build](https://travis-ci.org/oystparis/oyst-1click-magento/jobs/324675150#L270) like this.
First I think that was an issue about the last version of composer using a branch, but after some test I found this issue and it solved my problem.

If you need me to run some test, just ask ;)

**Comment by lenaorobei** [comment]
@mehdichaouch you are configuring `composer` installation to use repo.magento.com, but `dev-master` is available via `git` installation. Try to remove lines in your `composer.json` file.
```
    "repositories": {
        "magento-eqp": {
            "type": "git",
            "url": "https://github.com/magento/marketplace-eqp"
        }
```
And update `.travis.yml` file:
```
composer config repositories.magento-eqp git https://github.com/magento/marketplace-eqp && 
composer require "magento/marketplace-eqp:dev-master" &&
```

**Comment by mehdichaouch** [comment]
@lenaorobei you solution is working, same as mine [Travis](https://travis-ci.org/oystparis/oyst-1click-magento/jobs/327643508). The bad point is why we have to add magento-eqp repositories to make it work and why the last release is from [11 Apr 2017](https://github.com/magento/marketplace-eqp/issues/75)?
