### ISSUE TITLE
version 1.0.4 fails to run on php 5.4

### ISSUE THREAD

**Issue by centerax** [magento/marketplace-eqp#20]
PHP 5.4, supported by Magento1, fails to run MEQP1 on standard version 1.0.4

You can see the problem here: https://travis-ci.org/centerax/magemonkey/jobs/170160022

The error message is: **PHP Fatal error:  Call to undefined function MEQP1\Sniffs\Classes\array_column()**

**Comment by lenaorobei** [comment]
@centerax, thank you for reporting this issue. We opened an internal ticket to fix this bug.
