### ISSUE TITLE
Composer installable 

### ISSUE THREAD

**Issue by jamescowie** [magento/marketplace-eqp#23]
Can we make this a package on packagist so that the standard can be installed via composer just to make life easier ? It can then be added to projects without having to require this git repo.

**Comment by lenaorobei** [comment]
@jamescowie, unfortunately, Magento repositories on Packagist are not supported now, because they are moved to [repo.magento.com](http://repo.magento.com).

**Comment by danslo** [comment]
Could you keep the issue open until it's moved to repo.magento.com? Don't care so much about packagist vs repo.magento.com, it's more about _"added to projects without having to require this git repo"_.
