### ISSUE TITLE
Point of PSR1.Classes.ClassDeclaration.MissingNamespace for M1 ?

### ISSUE THREAD

**Issue by digitalpianism** [magento/marketplace-eqp#24]
In the M1 sniff ruleset, the following rule is included: `PSR1.Classes.ClassDeclaration.MissingNamespace`

With the following message: **"Each class must be in a namespace of at least one level"**

AFAIK, **it cannot be done with Magento 1 by default and you need your own autoloader to be able to achieve this.** 

So I reckon that's a problem and **that rule should be removed from the M1 ruleset.** I'm happy to do a PR if you can confirm or curious to hear about the reason if it is a good reason ^^

**Comment by lenaorobei** [comment]
@digitalpianism thank you for reporting. You're right, `PSR1.Classes.ClassDeclaration.MissingNamespace` should be removed from MEQP1 ruleset. Do not hesitate to open pull request to the `develop` branch.

**Comment by lenaorobei** [comment]
Fixed #25

**Comment by lenaorobei** [comment]
Fixed #25

**Comment by lenaorobei** [comment]
Bug still exists. The problem is that if you add one of the error codes with severity 10 (here `MultipleClasses` is an error code), CodeSniffer will automatically add all other error codes from sniff with default severity.
