### ISSUE TITLE
Conflictive array syntax in M1 and M2

### ISSUE THREAD

**Issue by mam08ixo** [magento/marketplace-eqp#3]
The coding standard MEQP1 [disallows _short_ array syntax](https://github.com/magento/marketplace-eqp/blob/1.0.1/MEQP1/ruleset.xml#L12) and the MEQP2 [disallows _long_ array syntax](https://github.com/magento/marketplace-eqp/blob/1.0.1/MEQP2/ruleset.xml#L40). While I perfectly understand this decision for the sake of consistency with the core code, it leads to a number of violations when using the _shared libraries_ approach.

Shared libraries, that is delivering _platform specific code_ to hook into one or the other major Magento version, accompanied by _framework independent code_ (the library) that provides functionality for reuse in both, M1 and M2.

![Magento Shared Libraries](https://www.integer-net.com/wp-content/uploads/sites/2/2016/01/magento-2-module-independent-library.png)
[Fabian Schmengler](https://github.com/schmengler) / [integer_net](https://www.integer-net.com/m1m2)

To overcome the current situation where the library cannot comply to the rules of both major versions, I suggest enforcing short array syntax in MEQP2 and accepting both in MEQP1 (i.e. remove the rule in question).

**Comment by schmengler** [comment]
Actually I'm against enforcing any Magento specific coding standards onto framework independent parts of an extension (i.e. library code), but nonetheless this sounds like a good idea.

The only reason to disallow short array syntax is if you want to require PHP 5.3 compatibility, right?

**Comment by ikruchynskyi** [comment]
@mam08ixo, forcing of short array syntax comes from our internal Magento2 coding [standards](https://github.com/magento/magento2/blob/develop/dev/tests/static/framework/Magento/Sniffs/Arrays/ShortArraySyntaxSniff.php). I agree with your suggestion - this rule shouldn't be strict for third party developers. I think that in nearest future it may transform into the warning for MEQP2 standard. But speaking about MEQP1, I couldn't be sure that it should be a warning. It's still the requirement for a lot of extensions which work with early Magento versions.

**Comment by mam08ixo** [comment]
@ikruchynskyi Short array syntax for M2 extensions is perfectly OK. But for M1 extensions, short _and_ long syntax should be allowed in my opinion.

**Comment by ikruchynskyi** [comment]
@mam08ixo I noticed Marketplace team, so will wait for their research results. We need to clarify how it will impact extension's quality before making the final decision. It all depends on a percentage of extensions which still require 5.3+.

**Comment by lenaorobei** [comment]
As mentioned above, running MEQP coding standards on independent libs or frameworks is not a good idea. So the reason to disallow short array syntax for MEQP1 is compatibility  with PHP 5.3. 
But anyway,  we've changed DisallowLongArraySyntax sniff to  [warning](https://github.com/magento/marketplace-eqp/blob/469b1e62f286e50e893633000f40c3d5c66b0604/MEQP2/ruleset.xml#L43-L45)  in MEQP2 ruleset.

**Comment by mam08ixo** [comment]
Active support of PHP 5.3 ended three years ago. PHP 5.4 is given as minimum required version for running a current M1 system. Sadly, this change is pretty much the opposite of what I tried to achieve: loosening the respective MEQP1 violation type.
