### ISSUE TITLE
Cant execute commande on Magento 2 extention

### ISSUE THREAD

**Issue by kooliahmd** [magento/marketplace-eqp#33]
When I execute this cmd : $ vendor/bin/phpcs [/path/to/your/extension] --standard=MEQP2

My php version is : PHP 5.6.23
I'm working on ubuntu14

**I get a fatal error saying :** 

PHP Fatal error:  Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Referenced sniff "MEQP1.Exceptions.Namespace" does not exist' in /home/a7med/projects/marketplace-eqp-master/magento-coding-standard/vendor/squizlabs/php_codesniffer/CodeSniffer.php:1150
Stack trace:
#0 /home/a7med/projects/marketplace-eqp-master/magento-coding-standard/vendor/squizlabs/php_codesniffer/CodeSniffer.php(763): PHP_CodeSniffer->_expandRulesetReference(Object(SimpleXMLElement), '/home/a7med/pro...', 0)
#1 /home/a7med/projects/marketplace-eqp-master/magento-coding-standard/vendor/squizlabs/php_codesniffer/CodeSniffer.php(562): PHP_CodeSniffer->processRuleset('/home/a7med/pro...')
#2 /home/a7med/projects/marketplace-eqp-master/magento-coding-standard/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(907): PHP_CodeSniffer->initStandard(Array, Array, Array)
#3 /home/a7med/projects/marketplace-eqp-master/magento-coding-standard/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(106): PHP_CodeSniffer_CLI->process()
#4 /home/a7med/projects in /home/a7med/projects/marketplace-eqp-master/magento-coding-standard/vendor/squizlabs/php_codesniffer/CodeSniffer.php on line 1150
a7med@a7med-PC:~/projects/marketplace-eqp-master/magento-coding-standard$

**Comment by quienti** [comment]
https://github.com/magento/marketplace-eqp/issues/31

**Comment by lenaorobei** [comment]
Please run `vendor/bin/phpcs --config-set installed_paths ../../..`
