### ISSUE TITLE
Warning : Session object MUST NOT be requested in constructor.

### ISSUE THREAD

**Issue by kooliahmd** [magento/marketplace-eqp#35]
I'm not sure this is the appropriate place to ask this question: 
After running phpcs , I got a warning saying :
```
Session object MUST NOT be requested in constructor.
It can only be passed as a method argument.
```

I searched on Magento2 doc, And I can't find another way to access Session object from an observer  context.
When I looked into Magento2 modules, I found that injecting session via constructor practice is widely used  
**Why Session object MUST NOT be requested in constructor?
What is the good practice to access Session?**

**Comment by mwgamble** [comment]
Are you using a session object directly (for example, `Magento\Catalog\Model\Session`) or are you using a proxy (for example, `Magento\Catalog\Model\Session\Proxy`)? Using the proxy ensures it is only actually instantiated (and therefore the session only initialised) when something actually calls a method on it to retrieve information from it.

You can find out more about proxy objects here: http://devdocs.magento.com/guides/v2.1/extension-dev-guide/proxies.html

**Comment by kooliahmd** [comment]
I'm actually accessing session directly without introducing a proxy.
I think the phpcs warning should be more comprehensible,like: 

> Session object MUST NOT be **injected directly** in constructor, **use a proxy**.
> It can only be passed as a method argument.
