### ISSUE TITLE
Update releases to 1.0.5.

### ISSUE THREAD

**Issue by centerax** [magento/marketplace-eqp#41]
Hi,

Can you update the releases tab and add 1.0.5?

Thanks.

**Comment by ikruchynskyi** [comment]
Hi @centerax!
We'll publish it ASAP, but, unfortunately, I can't tell certain date as we are overwhelmed. Sorry for that.

**Comment by centerax** [comment]
I understand you are busy but keeping this updated helps extension developers save time when uploading the extension to the Marketplace.

**Comment by lenaorobei** [comment]
@centerax, sorry for the delay. 
We are happy to inform you that new release is available now in both repositories - GitHub and [repo.magento.com](repo.magento.com)

**Comment by centerax** [comment]
Thanks @lenaorobei for your hard work.
