### ISSUE TITLE
It should work with PHP 5.5

### ISSUE THREAD

**Issue by mmenozzi** [magento/marketplace-eqp#42]
Hi,
Magento 2 modules which are declared as compatible with Magento 2.0.* should be compatible even with PHP 5.5 but this package is declared compatibile only with PHP >= 5.6.
So, if we put this package as a dev dependency of our extensions, it's not possible to run a continuous integration build with PHP 5.5 (the only option is to run `composer install --ignore-platform-reqs`)

So my question is: there is any reason that requires PHP ">=5.6" constraint? Can it be set to ">=5.5"?

**Comment by ikruchynskyi** [comment]
Hi @mmenozzi !
Thanks for input - we will check it and if it's possible - will publish it in 1.0.5 version.
