### ISSUE TITLE
Unescaped output detected for displayPrices()

### ISSUE THREAD

**Issue by IvanDotsenko** [magento/marketplace-eqp#48]
For method "displayPrices()" validator return warning 
"Unescaped output detected" 
Source: MEQP1.Templates.XssTemplate.FoundUnescaped

        <td>
            <?php echo $this->displayPrices(
                $this->getSource()->getBaseFeeAmount(),
                $this->getSource()->getFeeAmount()
            ); ?>
        </td>

**Comment by lenaorobei** [comment]
@IvanDotsenko according to Magento development best practice the output should be properly escaped in templates. PHP_CodeSniffer allows only static code check, so this sniff `MEQP1.Templates.XssTemplate.FoundUnescaped` detects that after `echo` there is no [allowed method](https://github.com/magento/marketplace-eqp/blob/master/MEQP1/Sniffs/Templates/XssTemplateSniff.php#L64-L73).
``` 
protected $allowedMethods = [
    'htmlEscape',
    'escapeHtml',
    'stripTags',
    'urlEscape',
    'escapeUrl',
    'jsQuoteEscape',
    'quoteEscape',
    'getId',
]; 
```
You can find more about templates XSS security [here](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/templates/template-security.html). It's Magento 2 documentation but for Magento 1.x rules are almost identical.

**Comment by IvanDotsenko** [comment]
@lenaorobei thanks for your response, but I didn't find solution for escaping method displayPrices()
In the core modules it don't escaped.  Could you advise some solution ?
