### ISSUE TITLE
Please specify the version of PHP_CodeSniffer in composer.json

### ISSUE THREAD

**Issue by danslo** [magento/marketplace-eqp#5]
The version that comes with Magento 2.1 (1.5.3) doesn't work with 1.0.1 of this repo.

**Comment by lenaorobei** [comment]
We added requirements to our [README.md](https://github.com/magento/marketplace-eqp/blob/master/README.md#requirements) file.

**Comment by danslo** [comment]
But can you add them to composer.json? That's kinda what it's for ;-)

**Comment by ikruchynskyi** [comment]
@danslo Do you mean that we need to add it into "require" section?  In case someone already has PHPCodesniffer - why he need to install another one? The main idea of custom standards is that they should be an addition to already exists Codesniffer standards.

**Comment by danslo** [comment]
Yeah, that's exactly what composer is for. If your repository doesn't work without that specific  dependency, it has a _require_ment on it.

By your logic, why specify `"php": ">=5.6.0"`, someone might already have PHP 5.4.

**Comment by ed007m** [comment]
@danslo Some of our sniffs doesn't work on php5.4.

**Comment by danslo** [comment]
And your code sniffs don't work _at all_ without PHP_CodeSniffer.

**Comment by ed007m** [comment]
And what if someone already use PHP_CodeSniffer?

**Comment by danslo** [comment]
- In the case of standalone checkout of marketplace-eqp, it's not a problem since codesniffer lives in its own vendor directory.
- In the case of some main project which has dependency on marketplace-eqp _and_ some specific version of codesniffer, this person should either;
  - relax their version requirement on codesniffer
  - choose between requiring marketplace-eqp _or_ a lower version of codesniffer, not both

In any of the above cases, marketplace-eqp repo should still be specific about its own requirements.

**Comment by ed007m** [comment]
There is one more case - when PHP_CodeSniffer lives as it's **own** application. In that case person needs only to specify path to MEQP standards or path to other standard they what. Without installing PHP_CodeSniffer for each standard. As example you can look how PhpStorm works. After specifing path to phpcs, all what you need is just to set path to your custom standard and it is ready to use.

Marketplace-eqp is not a standalone application (for now). In future, everything can change, and, ofcourse, we will add this requirement to composer. But now, it's just a standard like many others.

**Comment by danslo** [comment]
>Without installing PHP_CodeSniffer for each standard. 

If you don't care about dependency management, you're not forced to run composer install. At that point it will just be a guessing game if your *already installed random version of codesniffer* will work with these standards.

I also don't understand the comment about standalone applications. Libraries and/or standards shouldn't specify dependencies?

**Comment by ed007m** [comment]
@danslo I'm sorry for late response. Actually, now we are reviewing your recommendation with our architects. And we will notify you as soon as.

**Comment by ed007m** [comment]
@danslo we reviewed your proposition and PHP_CodeSniffer version will be added to composer.json file in next release.

Thank you for reporting.

**Comment by danslo** [comment]
Thank you!
