### ISSUE TITLE
Erroneous code sniff "The use of public non-interface method in ACTION is discouraged" in a Controller plugin

### ISSUE THREAD

**Issue by jantzenw** [magento/marketplace-eqp#51]
## Prerequisites
Marketplace EQP 1.0.5

## Steps to reproduce
1. Create a plugin on a controller with the path to the plugin involving the substring `Controller` somewhere.
2. On the `beforeExecute`/`afterExecute`/`aroundExecute` function, see that you receive the following erroneous code sniff: `The use of public non-interface method in ACTION is discouraged`. Example: https://www.screencast.com/t/Dcw3DdM0R

## Workaround
Create the plugin without using the word "Controller" in the file or folder structure.

## Analysis
Seems to be due to [`PublicNonInterfaceMethodsSniff::foundInAction`](https://github.com/magento/marketplace-eqp/blob/master/MEQP2/Sniffs/Classes/PublicNonInterfaceMethodsSniff.php#L145) looking for the substring "Controller" in the file path to determine if a class is a controller. 

## Possible solution
Possibly also look for the phrase `"public function execute("` or something similar to determine if a file is indeed a controller action? And/or check that the file's structure is specifically `<module top level folder>/Controller`, rather than looking for `Controller` anywhere? 

Not sure if either of these solutions are possible or desired.

**Comment by lenaorobei** [comment]
@jantzenw thanks for your reporting. You are right, PublicNonInterfaceMethodsSniff may find false-positive results. I think the solution with `<module top level folder>/Controller` makes sense. We can detect `registration.php` file to find module top level directory and then consider a Controller only in required folder.

**Comment by orlangur** [comment]
Custom sniffs are intended to make checks against concrete files, they should not access file system in any other way. So, while checking the presence of `registration.php` file would technically work it is not a good practice.

I see check of observers rely on `ObserverInterface`, why check of actions rely on directory hierarchy an not on `\Magento\Framework\App\ActionInterface`?

**Comment by lenaorobei** [comment]
@orlangur because it's a common practice when action classes extend some abstract classes.

**Comment by orlangur** [comment]
So? It will change after https://github.com/magento/magento2/issues/9582 is implemented, until then checks for `AbstractAction`/`Action` could be used together with `ActionInterface`, or even fallback to something like https://github.com/gamegos/php-code-sniffer/blob/master/src/Gamegos/CodeSniffer/Helpers/ClassHelper.php#L90

**Comment by shochdoerfer** [comment]
This also affects test cases, the EQP tool complains that the public test methods are not part of an interface.
