### ISSUE TITLE
Publish release to the public Packagist repo

### ISSUE THREAD

**Issue by mridang** [magento/marketplace-eqp#56]
Currently, we have to resort to using Github as a composer source. It would be good if we could pull the `marketplace-eqp` from Packagist e.g. https://packagist.org/packages/magento/

**Comment by lenaorobei** [comment]
We don't have an ability to pull this package to Packagist but it is available on [Magento Packages Repository](https://repo.magento.com).
You can install it by running
`composer create-project --repository=https://repo.magento.com magento/marketplace-eqp magento-coding-standard`
or
`composer config repositories.0 composer https://repo.magento.com`
`composer require magento/marketplace-eqp`
