### ISSUE TITLE
Too many "warnings" when sniffing phtml files

### ISSUE THREAD

**Issue by nocturnalfrog** [magento/marketplace-eqp#57]
Shouldn't .phtml files be excluded from the following rules in MEQP2?
- Generic.PHP.DisallowShortOpenTag.EchoFound
  > Short PHP opening tag used with echo; expected "<?php echo count ..." but found "<?= count ..."
- Squiz.ControlStructures.ControlSignature.SpaceAfterCloseParenthesis
  > Expected 1 space after closing parenthesis; found 0
- Squiz.ControlStructures.ControlSignature.SpaceAfterKeyword  
  > Expected 1 space after ELSE keyword; 0 found
- Generic.Files.LineLength.TooLong  
  > Line exceeds 120 characters; contains 136

These rules drown out the relevant warnings like 'MEQP2.Templates.XssTemplate.FoundUnescaped' and are probably the reason why most core .phtml files contain have a `// @codingStandardsIgnoreFile` annotation.

The lack of exceptions for .phtml files is driving people towards adding these 'ignore coding standards' annotations which is quite sad given how easy it would be to add the exclude patterns.

Any thoughts on this?
Should I create a Pull Request for this?
Am I missing some other rule that should be excluded?

**Comment by lenaorobei** [comment]
Fixed in #58
