### ISSUE TITLE
PHP Fatal error:  Class 'Generic_Sniffs_CodeAnalysis_EmptyStatementSniff' not found

### ISSUE THREAD

**Issue by kingsatti** [magento/marketplace-eqp#59]
hi,
i got this error and could find any way to fix this issue. 
PHP Fatal error:  Class 'Generic_Sniffs_CodeAnalysis_EmptyStatementSniff' not found in /home/user/marketplace-eqp/MEQP1/Sniffs/CodeAnalysis/EmptyBlockSniff.php on line 16

Can you guide me how i solve this issue i am using **PHP Version 7.1.8** and ubuntu 16.04.

Thanks

**Comment by lenaorobei** [comment]
@kingsatti could you please provide detailed steps (all commands) you run?

**Comment by kingsatti** [comment]
@lenaorobei  I figure it out by mysefl. you current version is not completable with  **PHP_CodeSniffer-3.0.2**. Downgrade to **PHP_CodeSniffer-2.0.8** working for me. Thanks for your time.

**Comment by lenaorobei** [comment]
@kingsatti to make sure all will work as expected, please install this coding standard via Composer. The required version of PHP_CodeSniffer is 2.6.2.
