### ISSUE TITLE
PHP_CodeSniffer 3.* Compatibility

### ISSUE THREAD

**Issue by sprankhub** [magento/marketplace-eqp#60]
It would be great if you could implement PHP_CodeSniffer 3.* compatibility. The ECG Coding standard is already compatible - see https://github.com/magento-ecg/coding-standard/pull/52. Hence, one currently needs to use different `phpcs` versions for EQP and ECG standards, which is quite unhandy.

**Comment by lenaorobei** [comment]
Fixed in #70
