### ISSUE TITLE
A false positive: «Namespace for class is not specified» on throwing a function call result

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/marketplace-eqp#61]
I have the following code:
```
catch (\Exception $e) {df_log($e); throw df_le($e);}
```
https://github.com/mage2pro/core/blob/2.12.20/Config/Backend.php#L64

The code sniffer reports: «**Namespace for df_le class is not specified**»

But `df_le` is not a class, it is a function:
```
function df_le(E $e) {return $e instanceof LE ? $e : new LE(__(df_ets($e)), $e);}
```
https://github.com/mage2pro/core/blob/2.12.20/Qa/lib/exception.php#L53-L58

So what should I do?

**Comment by ed007m** [comment]
Did you try to write code in PRS-2 coding standard?

**Comment by dmitrii-fediuk** [comment]
Will the PRS-2 coding standard resolve the false positive: «**Namespace for class is not specified**» on throwing a function call result?

**Comment by ed007m** [comment]
Of course. Also it will resolve all other issues that you have.
http://php.net/manual/en/language.namespaces.importing.php

**Comment by lenaorobei** [comment]
Closing this issue because this repo now contains sniffs for Magento 1.x code only.
Please refer to [magento/magento-coding-standard](https://github.com/magento/magento-coding-standard) for Magento 2.x coding standard.
