### ISSUE TITLE
A false positive: «Each class must be in a file by itself» on a conditional class declaration

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/marketplace-eqp#62]
I have the following code there:
```
if (@class_exists('\PHPUnit\Framework\TestCase')) {
    /** @noinspection PhpMultipleClassesDeclarationsInOneFile */
    abstract class TestCaseBase extends \PHPUnit\Framework\TestCase {}
}
else {
    /** @noinspection PhpMultipleClassesDeclarationsInOneFile */
    abstract class TestCaseBase extends \PHPUnit_Framework_TestCase {
```
https://github.com/mage2pro/core/blob/2.12.21/Core/TestCaseBase.php#L10-L16

The code sniffer reports a false positive: «**Each class must be in a file by itself**».

**Comment by lenaorobei** [comment]
@dmitry-fedyuk you should support different versions of your package for different Magento 2 releases. 
Please follow here for more information http://devdocs.magento.com/guides/v2.2/extension-dev-guide/versioning/
