### ISSUE TITLE
«Notice: Undefined index: fa_/chop in MEQP1/Sniffs/Security/DiscouragedFunctionSniff.php on line 252»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/marketplace-eqp#63]
`vendor/bin/phpcs <path to package> --standard=MEQP2 --severity=10` for the [2.12.27](https://github.com/mage2pro/core/tree/2.12.27) version of my [mage2pro/core](https://github.com/mage2pro/core) package leads to «**Notice: Undefined index: fa_/chop in MEQP1/Sniffs/Security/DiscouragedFunctionSniff.php on line 252**»:

![01](https://user-images.githubusercontent.com/83204/31007011-af10e178-a507-11e7-9d19-02ddb306de6d.png)

**Comment by lenaorobei** [comment]
@dmitry-fedyuk I fixed this issue in #68, however, I looked at your codebase and I highly recommend you to follow [Magento 2 technical guidelines](http://devdocs.magento.com/guides/v2.1/coding-standards/technical-guidelines/technical-guidelines.html).
