### ISSUE TITLE
Change Protector class member detector to private

### ISSUE THREAD

**Issue by Leonede** [magento/marketplace-eqp#7]
Hello, I found not logic rule.
https://github.com/magento/marketplace-eqp/blob/develop/MEQP2/Sniffs/PHP/ProtectedClassMemberSniff.php
Comment in line 13 says "Detects possible usage of 'private' scope modifiers.", and whole class detecting 'protected'. 
To fast fix: change `return [T_PROTECTED];` to `return [T_PRIVATE];` in line 32. And `protected $warningCode = 'FoundProtected';` to `protected $warningCode = 'FoundPrivate';`

Same on Russian:
Похоже что произошла ошибка, PHPCS с стилем MEQP2 говорит мне что protected переменные не желательны. А судя по комменту в коде детектора, должно искать private, а не protected.

Fixed file:
[ProtectedClassMemberSniff.php.txt](https://github.com/magento/marketplace-eqp/files/369471/ProtectedClassMemberSniff.php.txt)

**Comment by ikruchynskyi** [comment]
@Leonede , thank you for reporting. We will fix it in the next commit.

**Comment by lenaorobei** [comment]
Fixed typo in comment 810c1491232b9e19dfe388da3279700c4e81edc4.

**Comment by Leonede** [comment]
I expecting it will be another fix..
So, now  in Magento 2, protected methods and variables are not consumable? Which one I need to use then? 
Is private OK so?

**Comment by lenaorobei** [comment]
@Leonede, yes, all nop-public methods and properties should be private. For Magento 2 extension development we recommend using object composition over class inheritance. It makes your extension easier to maintain when class changes occur and update when new features need to be implemented. Follow [here](https://github.com/magento/magento2/issues/1019#issuecomment-72757989) for the detailed explanation.

**Comment by devamitbera** [comment]
@Leonede , it means if a protected  method is which is existing  at extended class,does not  override by  my own class  same rename method?
