### ISSUE TITLE
Can not pass EQP for a theme that included several modules

### ISSUE THREAD

**Issue by gizmocn** [magento/marketplace-eqp#72]
I try to submit a theme to Magento MarketPlace, but I can not pass marketplace-eqp, both theme and modules is obeyed official file structure and with composer.json file, but I have no idea how to package both theme and modules together to pass EQP.
My theme has some plugins so the directory structure is like:

app

    code
    -- Cattheme
    --- Ajaxfilter
    --- Base
    --- Install
    --- Megamenu
    --- Themeconfig
    design
    -- frontend
    --- Cattheme
    ---- rabel

pub

    media
    -- themeconfig

I got error:

"composer.json" file missing.
"registration.php" file missing.
"theme.xml" file missing.

How can I submit a theme with plugins to Marketplace?

**Comment by lenaorobei** [comment]
Hello @gizmocn, please have a look at [a typical Magento theme file structure](http://devdocs.magento.com/guides/v2.2/extension-dev-guide/build/module-file-structure.html).

Closing this issue because it's not related to the Magento Extension Quality Coding Standard.
