### ISSUE TITLE
MEQP1 does not working properly

### ISSUE THREAD

**Issue by sankar1061** [magento/marketplace-eqp#73]
We have executed the below command,

phpcs --standard=MEQP1 module/

But throw below errors:

PHP Fatal error:  Interface 'PHP_CodeSniffer\Sniffs\Sniff' not found in /var/www/marketplace-eqp-master/MEQP1/Sniffs/Classes/Mysql4Sniff.php on line 15

How to resolve this issue.

**Comment by lenaorobei** [comment]
Hello @sankar1061! Could you please provide steps to reproduce? Describe your environment (OS, PHP version, etc) and how you've installed MEQP standard?

**Comment by sankar1061** [comment]
Helloo @lenaorobei

My system details.
    OS  - Ubuntu 16.04.3
    PHP -  7.0.18

MEQP installed below method.
    1) I have download the marketplace-eqp-master package.
    2) executed the commands ( sudo phpcs --config-set installed_paths /var/www/marketplace-eqp-master/ ).
    3) Run the command phpcs -i
    4) Displayed ( The installed coding standards are PSR1, MySource, PEAR, PSR2, PHPCS, Zend, Squiz, MEQP2 and MEQP1 )

**Comment by lenaorobei** [comment]
Did you run `composer install` inside marketplace-eqp-master folder?

**Comment by sankar1061** [comment]
Yes already installed the composer

**Comment by lenaorobei** [comment]
I suspect you have `phpcs` installed globally, and you didn't install MEQP standard correctly. I mean, you need to:
1. `cd /var/www/marketplace-eqp-master` 
2. Run `composer install` command to install all dependencies
3. vendor/bin/phpcs --standard=MEQP1 module/

**Comment by sankar1061** [comment]
One month before, I have check the same everything working fine. But now update the folder structure in marketplace-eqp-master. In marketplace-eqp-master added the  MEQP/Utils folder. But one month before does not available. I have try to installed the old package and executed the MEQP1, all are working.

**Comment by sankar1061** [comment]
Please refer the my old package >> 
[marketplace-eqp-master.zip](https://github.com/magento/marketplace-eqp/files/1481910/marketplace-eqp-master.zip)

**Comment by lenaorobei** [comment]
Yes, that's correct. We updated MEQP Standard by adding new dynamic sniffs and also installation steps were changed. Please follow the instruction.

**Comment by sankar1061** [comment]
How to install the dynamic sniffs.

My system details.
OS - Ubuntu 16.04.3
PHP - 7.0.18

**Comment by lenaorobei** [comment]
Installation instructions are available in [README.md](https://github.com/magento/marketplace-eqp#dynamic-sniffs) file.
