### ISSUE TITLE
PHP Fatal error:  Trait 'MEQP\Utils\Helper' not found

### ISSUE THREAD

**Issue by sankar1061** [magento/marketplace-eqp#74]
We have checked the MEQP1 standard. But throw below mentioned errors,

**PHP Fatal error:  Trait 'MEQP\Utils\Helper' not found in /var/www/development/marketplace-eqp-master/MEQP1/Sniffs/Classes/ResourceModelSniff.php on line 21**

**My system details.**
OS - Ubuntu 16.04.3
PHP - 7.0.18

How to solve this issue.....!

**Comment by lenaorobei** [comment]
@sankar1061 please provide steps to reproduce.

**Comment by sankar1061** [comment]
@lenaorobei please refer the below:-
1. We have checked the installed coding standard - **phpcs -i**
_output:_
**The installed coding standards are Squiz, PEAR, PSR1, Zend, MySource, PSR2, MEQP2 and MEQP**1

2. We have run MEQP2 - **phpcs --standard=MEQP1 module/ > error.txt**
_output:_
**PHP Fatal error: Trait 'MEQP\Utils\Helper' not found in /var/www/development/marketplace-eqp-master/MEQP1/Sniffs/Classes/ResourceModelSniff.php on line 21**

> My phpcs version are:

 _PHP_CodeSniffer version 3.1.1 (stable)_
Note: 
We have install the coding standard via composer everything working fine (composer create-project --repository=https://repo.magento.com magento/marketplace-eqp magento-coding-standard).
But installed via _clone download_ not working.

**Comment by lenaorobei** [comment]
@sankar1061 if you want to install via `git clone`, you should run `composer install` in the `/var/www/development/marketplace-eqp-master` folder.

**Comment by lenaorobei** [comment]
@sankar1061 did this solve the issue?

**Comment by sankar1061** [comment]
@lenaorobei 
Install via _clone -> **MEQP** folder are available. But Install via _composer-> does not available **MEQP** folder.
So Which step (clone or composer) to installation correct.

**Comment by lenaorobei** [comment]
@sankar1061 both options are correct.

**Cloning GitHub repository requires following steps:**
1. `$ cd /var/www/development/`
2. `$ git clone git@github.com:magento/marketplace-eqp.git`
3. `$ cd marketplace-eqp`
4. `$ composer install`

**Installation via Composer requires following steps:**
1. `$ cd /var/www/development/`
2. `$ composer create-project --repository=https://repo.magento.com magento/marketplace-eqp magento-coding-standard`
3. `$ cd magento-coding-standard`

**Comment by sankar1061** [comment]
We have run **sudo git clone git@github.com:magento/marketplace-eqp.git**
 But throw below mentioned error:

> Cloning into 'marketplace-eqp'...
> The authenticity of host 'github.com (192.30.253.112)' can't be established.
> RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
> Are you sure you want to continue connecting (yes/no)? yes
> Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

**Comment by lenaorobei** [comment]
You need to [generate SSH key](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/) or to use HTTPS to clone.
`git clone https://github.com/magento/marketplace-eqp.git`

**Comment by lenaorobei** [comment]
@sankar1061 did you succeed to install the package?

**Comment by lenaorobei** [comment]
Closing this issue.
@sankar1061 feel free to open a new one if you experienced any problems.

**Comment by erwinesphere** [comment]
hi @lenaorobei i got same issue with @sankar1061 

at my marketplace-eqp git clone folder i run this command:

Erwins-MacBook-Pro:marketplace-eqp erwintan$ /Users/erwintan/PHP_CodeSniffer/bin/phpcs /Users/erwintan/workspace/extension-magento1/ --standard=MEQP1

PHP Fatal error:  Trait 'MEQP\Utils\Helper' not found in /Users/erwintan/workspace/marketplace-eqp/MEQP1/Sniffs/Classes/ResourceModelSniff.php on line 21

i'm using git clone and composer install.

**Comment by lenaorobei** [comment]
@erwinesphere could you please provide exact steps to reproduce and info about environment you're using?

**Comment by r-martins** [comment]
#114 duplicates this issue, which is not solved yet. :(
