### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by schmengler** [magento/marketplace-eqp#75]
It's been > 7 months since the last release and a few updates have been made since then. Are there any plans for a new release?

**Comment by diazwatson** [comment]
+1

**Comment by andrewkett** [comment]
+1 as would love phpcs 3.* support from https://github.com/magento/marketplace-eqp/pull/70 in a release

**Comment by centerax** [comment]
hello, any eta for a new release?

**Comment by centerax** [comment]
@lenaorobei 🤔

**Comment by lenaorobei** [comment]
Sorry for late response. 
I order to keep MEQP releases up to date with the current extension verification process, we need not only to create new release here on GitHub (as well as repo.magento.com) but also we need to update our internal tools. This is the only reason for such delay. We are working on it and I will keep you updated.

**Comment by lenaorobei** [comment]
2.0.0 release is [available now on GitHub](https://github.com/magento/marketplace-eqp/releases/tag/2.0.0) as well as on repo.magento.com

Sorry for such long delay.
