### ISSUE TITLE
A false positive: «The use of public non-interface method in ACTION is discouraged» when extending parent classes

### ISSUE THREAD

**Issue by shochdoerfer** [magento/marketplace-eqp#76]
When running EQP against our [Force Login](https://github.com/bitExpert/magento2-force-login) module the warning "The use of public non-interface method in ACTION is  discouraged" shows up for this piece of [code](https://github.com/bitExpert/magento2-force-login/blob/master/Controller/LoginRouter.php#L67). The method in question is part of an interface implemented by the class our class is extending from thus the warning does not seem correct to me.

The warning can be avoided by letting our class implement the interface in question. This means the sniff does not check interfaces implemented by all parent classes but just the interfaces by the class in question.

**Comment by nntoan** [comment]
Please re-open, the pull request does not look right to me. `ActionInterface` allowed only `execute()` method. What if we use `ActionInterface` different than `Framework\App\ActionInterface` such as:

![screenshot 2018-12-05 11 43 51](https://user-images.githubusercontent.com/3891429/49490552-2df16880-f883-11e8-9092-13f8f98b459e.png)

**Comment by lenaorobei** [comment]
@nntoan feel free to create a new issue regarding this particular case.
Now MEQP rules do not allow dynamic code check, so all we can rely is a class (interface) name string. This is the reason why this sniff is marked with severity 8 , not 10. In theory it can return false-positive finding.
