### ISSUE TITLE
how to check before git commit

### ISSUE THREAD

**Issue by sunilit42** [magento/marketplace-eqp#79]
Hello,

we are using grumphp  for code check and we want to check code some body do commit into git.

is that possible to add that script into grumphp?

**Comment by lenaorobei** [comment]
Hello @sunilit42,
I think this question is not related to MEQP coding standard. `grumphp` docs can help you - https://github.com/phpro/grumphp/blob/master/doc/tasks/phpcs.md#magento
You can add standard in the same way by running:
`composer require --dev magento/marketplace-eqp`

**Comment by sunilit42** [comment]
@lenaorobei 

thanks for reply.

I already configure and working fine but how to check only 10 level severity

how to pass via grumphp.xml file?

**Comment by lenaorobei** [comment]
Try to add `show_warnings: false` parameter. It might work because only errors have 10 level severity.
