### ISSUE TITLE
Abstract methods and  "Use of protected class members is discouraged."

### ISSUE THREAD

**Issue by likemusic** [magento/marketplace-eqp#83]
There is impossible to have abstract private method in php. Therefore the message should not be displayed for them.

**Comment by lenaorobei** [comment]
The principle Composition over inheritance implies that you can build your architecture without the use of abstract methods. You can create an interface, implement it and inject via constructor.
Please find more in the [Magento Technical guidelines](https://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html)

**Comment by likemusic** [comment]
In this case, it would be more logical/obvious/informative  to show a message like "Use of abstract classed is discouraged.".

**Comment by lenaorobei** [comment]
Thanks for the feedback. Will take it into account.
