### ISSUE TITLE
Is it possible to run this on windows?

### ISSUE THREAD

**Issue by Tropicalista** [magento/marketplace-eqp#86]
I'm trying to run the script on windows, but I get this error:
```
dir=$(d=${0%[/\\]*}; cd "$d"; cd "../squizlabs/php_codesniffer/scripts" && pwd)

##See if we are running in Cygwin by checking for cygpath program
if command -v 'cygpath' >/dev/null 2>&1; then
        # Cygwin paths start with /cygdrive/ which will break windows PHP,
        # so we need to translate the dir path to windows format. However
        # we could be using cygwin PHP which does not require this, so we
        # test if the path to PHP starts with /cygdrive/ rather than /usr/bin
        if [[ $(which php) == /cygdrive/* ]]; then
                dir=$(cygpath -m "$dir");
        fi
fi

dir=$(echo $dir | sed 's/ /\ /g')
"${dir}/phpcs" "$@"
```

**Comment by lenaorobei** [comment]
Hello @Tropicalista.

As far as I can see this script is not related to Magento Extension Quality Program coding standard. Maybe I'm missing something. If yes please add more information what are you trying to achieve.

Thank you.

**Comment by Tropicalista** [comment]
Hi @lenaorobei,

I'm trying to check my extension with this script. I followed the readme instructions, and run the script:

```    
php vendor/bin/phpcs F:\Progetti\CodeCanyon\Refactoring\depot\magento-coding-standard\myapp --standard=MEQP2
```
and that error came out.

**Comment by lenaorobei** [comment]
@Tropicalista could you please provide steps to reproduce and detailed info about environment you're using?

**Comment by lenaorobei** [comment]
@Tropicalista feel free to reopen the task with detailed steps to reproduce if you still experience the same issue.
