### ISSUE TITLE
getting error while install

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/marketplace-eqp#9]
where to run this command "composer require magento/marketplace-eqp".

every time i got this error : 
[InvalidArgumentException]
  Could not find package magento/marketplace-eqp at any version for your minimum-stability (stable). Check the packag
  e spelling or your minimum-stability

Please help me properly setup this.

**Comment by ikruchynskyi** [comment]
Hi, @ankursachdeva11. This is known issue - you can use solution from this topic https://github.com/magento/marketplace-eqp/issues/2. Unfortunately, we cannot add this repo on Packagist, so this is the only way to solve this problem.
